---
- name: Apply OperatorGroups from a directory
  block:
    - name: Enumerate all .yml and .yaml files in the operatorgroups directory
      ansible.builtin.find:
        paths: "artifacts/operatorgroups"
        patterns: ["*.yml.j2","*.yaml.j2","*.yml","*.yaml"]
        recurse: no
      register: manifest_files

    - name: Create the OperatorGroups in the cluster
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', item.path) | from_yaml }}"
      loop: "{{ manifest_files.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
