---
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-variables
  namespace: argocd
data:
  KUSTOMIZE_PLUGIN_HOME: /etc/kustomize/plugin
  CLUSTER_NAME: '${cluster_name}'
  CLUSTER_BASE_DOMAIN: '${cluster_base_domain}'
          # all created clusters base domain should be <cluster-name>.<PLATFORM_BASE_DOMAIN> 
  PLATFORM_BASE_DOMAIN: '${platform_base_domain}'
  INFRA_GITOPS_REPO: '${gitops_repo}'        
